### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by wimspaargaren** [wimspaargaren/information-retrieval-project#13]
Avoid:

- [x] You can do amazing things
- [x] All kind of cool applications
- [x] Nice overview
- [x] Generic stuff

Do:

- [x] Use academic language
- [x] Use more tables or diagrams to omit text

Further check slack for feedback of achilleas & https://github.com/wimspaargaren/information-retrieval-project/blob/master/Meetings/project-idea-feedback.md

Last check:
- [x] Check that all figures/images have a title and number the figures
- [x] Add overall title "Amsterdam In Motion"

**Comment by daanschipper** [comment]
Reference figures/tables as follows:
_Figure figure-daan-uniqueclassifier: This is a figure_

And reference in text to that figure as "As seen in Figure figure-daan-uniqueclassifier, bla bla".

That way we can easily replace all figures by their corresponding number.
